### ISSUE TITLE
What is _M referring to?

### ISSUE THREAD

**Issue by develephant** [Kong/lua-resty-timer#1]
Hi,

This looks like a great module. I am a little stumped on what this line refers to:

```
-- anchor the object and timer
 _M.global_object = object     -- will be collected if not anchored
```

I don't see any reference to that in the docs https://kong.github.io/lua-resty-timer/index.html#new

Any clarification appreciated.

-dev

**Comment by Tieske** [comment]
This is a common Lua idiom. `_M` usually refers to a module table, see https://github.com/Kong/lua-resty-dns-client/blob/master/src/resty/dns/utils.lua for an example.

In the example code:
```lua
  -- anchor the object and timer
  _M.global_object = object     -- will be collected if not anchored
```
It is assumed the timer is used in some module with a module table called `_M` and then the timer is attached to that table to prevent it from being garbage collected.
