### ISSUE TITLE
shm by name 'timer_shm' not found 

### ISSUE THREAD

**Issue by BhanuPrakash531** [Kong/lua-resty-timer#5]
Got the error message` *56 lua coroutine: runtime error: /usr/local/share/lua/5.1/resty/timer.lua:244: shm by name 'timer_shm' not found `with the below options or configurations

```
local options = {
            interval = 2,           -- expiry interval in seconds
            recurring = true,         -- recurring or single timer
            immediate = false,         -- initial interval will be 0
            detached = false,         -- run detached, or be garbagecollectible
            expire = object.handler,  -- callback on timer expiry
            cancel = function(reason, self, param1)
                -- will be called when the timer gets cancelled
				print("Cancelling "..reason.." ".." self"..param1)
            end,
             shm_name = "timer_shm",   -- shm to use for node-wide timers
             key_name = "my_key",      -- key-name to use for node-wide timers
            -- sub_interval = 0.1,       -- max cross worker extra delay
        }
```

How to solve this issue? I need to run only 1 timer at a time and this can be achieved through shm_name.

**Comment by Tieske** [comment]
In your nginx configuration you need the lua_shared_dict directive, as shown here: https://github.com/Kong/lua-resty-timer#synopsis

**Comment by BhanuPrakash531** [comment]
> In your nginx configuration you need the lua_shared_dict directive, as shown here: https://github.com/Kong/lua-resty-timer#synopsis

@Tieske very helpful. I missed it somehow. Thanks and cheers
