### ISSUE TITLE
2019/09/07 17:06:28 [error] 3265#3265: init_worker_by_lua error: init_worker_by_lua:1: unexpected symbol near '/'

### ISSUE THREAD

**Issue by sixtool** [Kong/lua-resty-timer#6]
`local timer = require("resty.timer")
local object = {
    count = 0,
    handler = function(self, param1)
        ngx.log(ngx.ERR, "------")
    end,
    timer = nil
}

local options = {
     interval = 1,
     recurring = true,
     immediate = true,
     detached = false,
     expire = object.handler,
     cancel = function(reason,self,param1)

     end,
     shm_name = "timer_shm",
     key_name = "my_key",
     sub_interval = 0.1
}
object.timer = timer(options,object,"param1")`

**Comment by Tieske** [comment]
Not sure what you did to get this error, but that's a compilation error if in not mistaken. So that was not generated by this module.

**Comment by Tieske** [comment]
Closing due to lack of response
